### ISSUE TITLE
Gap between list items (not minified)

### ISSUE THREAD

**Issue by jedmao** [inuitcss/objects.list-inline#4]
For those who aren't terribly familiar w/ the side effects of inline-block, I think it's worth mentioning that there will be a gap between list items if you don't minify your HTML. Example: http://jsfiddle.net/co39wren/

**Comment by csshugs** [comment]
As this is still pre-alpha, I close this for now. We will definitely put a note in the documentation when we release the next major version of inuitcss.

@jedmao Thank you very much for pointing this out, though!
