### ISSUE TITLE
Could be renamed in list-inline-block and a real list-inline could be created

### ISSUE THREAD

**Issue by dominiquevilain** [inuitcss/objects.list-inline#5]
The actual name may be confusing. 

If you have to tag a real content-related inline list like the following one :
```html
<p>We are split in 4 groups:</p>
<ol>
    <li>2184, </li>
    <li>2185, </li>
    <li>2186, </li>
    <li>2187.</li>
</ol>
```
and want it rendered like that : 
*We are split in 4 groups: 2184, 2185, 2186, 2187.*, the most reasonable choice seems to be to use a class for the `ol`, named `list-inline`. The `inline-block` behavior is not suitable for this one because the `li`are still seen as blocks, and the words and spaces are not used any more in the calculation of the word wrapping behavior. Each list-item becomes a single blocky *word*, even if it is made of several actual words. 

I understand that from a structural point of view (like when you need to style a navigation list), it makes sense to think about the list as an inline-list and thus provide an `inline-block`style, but from a typographic point of view, an inline list should probably behave like a regular sentence, aligning actual words one after the other.

Wouldn’t it be interesting to create another object for the list-inline-block behavior and keep the inline-list behavior for typographic purposes ?

**Comment by anselmh** [comment]
Kinda makes sense to me, semantically from the naming. One issue is that people actively use this package already so we can’t simply alter the behavior of it (unless we make it a breaking major version change which would be possible of course).

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this issue is still relevant, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks for your time and your effort.
